"""Running the access point that other devices join.

hostapd is used directly rather than through NetworkManager's shared mode,
because shared mode starts its own dnsmasq and takes port 53 -- the one port
this whole program needs. NetworkManager remains a fallback for hosts where
hostapd is not installed, with the DNS conflict worked around.

The link to clients is WPA3-SAE where the client supports it, falling back to
WPA2 on the same SSID. SAE replaces WPA2's pre-shared-key handshake with a
password-authenticated key exchange, which means a captured handshake cannot be
attacked offline with a wordlist -- the difference between a weak passphrase
being a risk and being an inconvenience.
"""

from __future__ import annotations

import ipaddress
import logging
import os
import shutil
import signal
import subprocess
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path

log = logging.getLogger(__name__)


class HotspotError(RuntimeError):
    """The access point could not be started."""


@dataclass
class HotspotConfig:
    interface: str
    ssid: str
    passphrase: str
    subnet: ipaddress.IPv4Network
    channel: int = 6
    band: str = "2.4"
    country_code: str = "US"
    hidden: bool = False
    #: WPA3 only. More secure, but silently excludes older devices, so the
    #: default is the transition mode that accepts both.
    wpa3_only: bool = False
    #: Stop clients from talking to each other. Right for a guest network,
    #: wrong if you want to cast to a TV through the hotspot.
    client_isolation: bool = False

    @property
    def router_address(self) -> str:
        return str(next(self.subnet.hosts()))


def hostapd_available() -> bool:
    return shutil.which("hostapd") is not None


def nmcli_available() -> bool:
    return shutil.which("nmcli") is not None


def build_hostapd_config(config: HotspotConfig) -> str:
    """Render a hostapd configuration."""
    if len(config.passphrase) < 8:
        raise HotspotError("the hotspot passphrase must be at least 8 characters")
    if not 1 <= len(config.ssid) <= 32:
        raise HotspotError("the hotspot SSID must be 1-32 characters")

    if config.band == "5":
        hw_mode, channel = "a", config.channel or 36
        # 80MHz VHT on 5GHz; the centre-frequency index is fixed to the first
        # 80MHz block, which is where channel 36 sits.
        band_lines = [
            "ieee80211ac=1",
            "vht_oper_chwidth=1",
            "vht_oper_centr_freq_seg0_idx=42",
            "vht_capab=[SHORT-GI-80]",
        ]
    else:
        hw_mode, channel = "g", config.channel or 6
        band_lines = ["ieee80211n=1", "wmm_enabled=1", "ht_capab=[HT40+][SHORT-GI-20][SHORT-GI-40]"]

    if config.wpa3_only:
        # SAE alone, with management-frame protection required, which WPA3
        # mandates and which blocks deauthentication attacks.
        security = [
            "wpa=2",
            "wpa_key_mgmt=SAE",
            "ieee80211w=2",
            f"sae_password={config.passphrase}",
        ]
    else:
        # Transition mode: WPA3 for devices that understand SAE, WPA2 for the
        # rest, on one SSID.
        security = [
            "wpa=2",
            "wpa_key_mgmt=WPA-PSK WPA-PSK-SHA256 SAE",
            "ieee80211w=1",
            "sae_require_mfp=1",
            f"wpa_passphrase={config.passphrase}",
            f"sae_password={config.passphrase}",
        ]

    lines = [
        "# Generated by WiFiGuard.",
        f"interface={config.interface}",
        "driver=nl80211",
        f"ssid={config.ssid}",
        f"country_code={config.country_code}",
        "ieee80211d=1",
        f"hw_mode={hw_mode}",
        f"channel={channel}",
        *band_lines,
        "auth_algs=1",  # Open system authentication only; shared key is broken.
        f"ignore_broadcast_ssid={1 if config.hidden else 0}",
        f"ap_isolate={1 if config.client_isolation else 0}",
        "wpa_pairwise=CCMP",
        "rsn_pairwise=CCMP",
        *security,
        # Rotate the group key regularly so a departing client cannot decrypt
        # later broadcast traffic.
        "wpa_group_rekey=600",
        "wpa_gmk_rekey=86400",
        "disassoc_low_ack=1",
    ]
    return "\n".join(lines) + "\n"


class Hotspot:
    """Owns the hostapd process and the access point's address."""

    def __init__(self, config: HotspotConfig) -> None:
        self.config = config
        self._process: subprocess.Popen | None = None
        self._config_path: Path | None = None
        self._address_added = False
        self._used_nmcli = False

    @property
    def running(self) -> bool:
        if self._used_nmcli:
            return True
        return self._process is not None and self._process.poll() is None

    def start(self) -> None:
        self._configure_address()
        if hostapd_available():
            self._start_hostapd()
        elif nmcli_available():
            self._start_nmcli()
        else:
            raise HotspotError(
                "neither hostapd nor nmcli is installed. Install hostapd "
                "(Debian/Ubuntu: apt install hostapd) to run the access point."
            )

    def _configure_address(self) -> None:
        """Give the AP interface its address and bring it up."""
        address = f"{self.config.router_address}/{self.config.subnet.prefixlen}"
        _run(["ip", "link", "set", self.config.interface, "up"], check=False)
        result = _run(
            ["ip", "addr", "add", address, "dev", self.config.interface], check=False
        )
        # "File exists" means the address is already configured, which is fine.
        if result.returncode not in (0, 2):
            log.warning(
                "could not add %s to %s: %s",
                address,
                self.config.interface,
                result.stderr.strip(),
            )
        else:
            self._address_added = True

    def _start_hostapd(self) -> None:
        # Some distributions ship a masked hostapd unit that would fight us for
        # the interface; stopping it first is harmless when it is not running.
        _run(["systemctl", "stop", "hostapd"], check=False)

        handle = tempfile.NamedTemporaryFile(
            mode="w", suffix=".conf", prefix="wifiguard-hostapd-", delete=False
        )
        handle.write(build_hostapd_config(self.config))
        handle.close()
        self._config_path = Path(handle.name)
        os.chmod(self._config_path, 0o600)  # The passphrase is in this file.

        log.info(
            "starting hostapd on %s: SSID %r, channel %d",
            self.config.interface,
            self.config.ssid,
            self.config.channel,
        )
        self._process = subprocess.Popen(
            ["hostapd", str(self._config_path)],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
        )

        # hostapd fails fast on a driver that cannot do AP mode, so a short wait
        # turns a silent failure into a useful message.
        time.sleep(2)
        if self._process.poll() is not None:
            output = self._process.stdout.read() if self._process.stdout else ""
            self._cleanup_config()
            raise HotspotError(
                f"hostapd exited immediately:\n{output.strip()}\n\n"
                f"The usual cause is that {self.config.interface} does not support AP mode, "
                f"or is still managed by NetworkManager. Try "
                f"`nmcli device set {self.config.interface} managed no` first, and check "
                f"`iw list` for \"AP\" under supported interface modes."
            )

    def _start_nmcli(self) -> None:
        log.info("hostapd is not installed; falling back to NetworkManager")
        result = _run(
            [
                "nmcli", "device", "wifi", "hotspot",
                "ifname", self.config.interface,
                "ssid", self.config.ssid,
                "password", self.config.passphrase,
            ],
            check=False,
        )
        if result.returncode != 0:
            raise HotspotError(f"nmcli could not start the hotspot: {result.stderr.strip()}")
        self._used_nmcli = True
        log.warning(
            "NetworkManager's hotspot runs its own dnsmasq on port 53. WiFiGuard's "
            "firewall rules redirect client DNS to us regardless, but installing "
            "hostapd gives a cleaner setup."
        )

    def stop(self) -> None:
        if self._process is not None and self._process.poll() is None:
            self._process.send_signal(signal.SIGTERM)
            try:
                self._process.wait(timeout=5)
            except subprocess.TimeoutExpired:
                self._process.kill()
                self._process.wait(timeout=5)
            log.info("hostapd stopped")
        self._process = None
        self._cleanup_config()

        if self._used_nmcli:
            _run(["nmcli", "connection", "down", "Hotspot"], check=False)
            self._used_nmcli = False

        if self._address_added:
            address = f"{self.config.router_address}/{self.config.subnet.prefixlen}"
            _run(["ip", "addr", "del", address, "dev", self.config.interface], check=False)
            self._address_added = False

    def _cleanup_config(self) -> None:
        if self._config_path is not None:
            try:
                self._config_path.unlink(missing_ok=True)
            except OSError:
                pass
            self._config_path = None

    def clients(self) -> list[dict[str, str]]:
        """Associated stations, from hostapd's control interface."""
        if not shutil.which("hostapd_cli"):
            return []
        result = _run(["hostapd_cli", "-i", self.config.interface, "all_sta"], check=False)
        if result.returncode != 0:
            return []

        stations: list[dict[str, str]] = []
        current: dict[str, str] = {}
        for line in result.stdout.splitlines():
            line = line.strip()
            if not line:
                continue
            if ":" in line and "=" not in line:
                if current:
                    stations.append(current)
                current = {"mac": line}
            elif "=" in line and current:
                key, _, value = line.partition("=")
                if key in ("signal", "rx_bytes", "tx_bytes", "connected_time"):
                    current[key] = value
        if current:
            stations.append(current)
        return stations


def _run(command: list[str], check: bool = True) -> subprocess.CompletedProcess:
    if shutil.which(command[0]) is None:
        return subprocess.CompletedProcess(command, 127, "", f"{command[0]} is not installed")
    try:
        result = subprocess.run(command, capture_output=True, text=True, timeout=20, check=False)
    except (OSError, subprocess.TimeoutExpired) as exc:
        raise HotspotError(f"{' '.join(command)}: {exc}") from exc
    if check and result.returncode != 0:
        raise HotspotError(f"{' '.join(command)} failed: {result.stderr.strip()}")
    return result


def pick_channel(band: str = "2.4") -> int:
    """Choose a channel, preferring one that is not already crowded.

    Falls back to the usual non-overlapping defaults when no scan is available.
    """
    if band == "5":
        return 36
    if shutil.which("iw") is None:
        return 6

    # Count the access points already on each non-overlapping 2.4GHz channel.
    counts = {1: 0, 6: 0, 11: 0}
    result = _run(["iw", "dev"], check=False)
    device = ""
    for line in result.stdout.splitlines():
        if line.strip().startswith("Interface"):
            device = line.split()[-1]
            break
    if not device:
        return 6

    scan = _run(["iw", "dev", device, "scan", "dump"], check=False)
    for line in scan.stdout.splitlines():
        stripped = line.strip()
        if stripped.startswith("DS Parameter set: channel"):
            try:
                channel = int(stripped.split()[-1])
            except ValueError:
                continue
            # Attribute each network to the nearest non-overlapping channel.
            nearest = min(counts, key=lambda candidate: abs(candidate - channel))
            counts[nearest] += 1
    return min(counts, key=lambda channel: counts[channel])
